# frozen_string_literal: true

source "https://rubygems.org"

gem "sinatra"
gem "rack"
gem "rack-contrib"
gem "rubysl-base64"

group :development, :test do
  gem "standard", "~> 1.33"
  gem "puma"
end
